name 'lelama-profile_d'
version '0.1.0'

author 'lelama'
license 'Apache Version 2.0'
project_page 'http://github.com/lelama/lelama-profile_d.git'
source 'git://github.com/lelama/lelama-profile_d.git'
summary 'profile.d Module'
description 'profile.d Module for RHEL, CentOS, Debian, Ubuntu'
dependency 'puppetlabs/stdlib', '>=3.2.0'
