name 'puppet-profile_d'
version '0.1.0'

author 'marcgascon'
license 'Apache Version 2.0'
project_page 'http://github.com/marcgascon/puppet-profile-d.git'
source 'git://github.com/marcgascon/puppet-profile-d.git'
summary 'profile-d Module ables you to manage files under /etc/profile.d/'
description 'profile.d Module for RHEL, CentOS, Debian, Ubuntu'
dependency 'puppetlabs/stdlib', '>=3.2.0'
